-- =====================================================================
-- Albsale Vlora — SAP HANA Cloud · KPI views (SQL views mbi star schema)
-- Këto pamje ushqejnë dashboard-in analitik (KPI cards + charts).
-- Schema: ALBSALE_ANALYTICS
-- =====================================================================
SET SCHEMA "ALBSALE_ANALYTICS";

-- 1) Funnel-i i statuseve O2C (numri i porosive për status)
CREATE OR REPLACE VIEW "V_KPI_STATUS_FUNNEL" AS
SELECT "ORDER_STATUS" AS "STATUS", COUNT(*) AS "ORDERS", SUM("VALUE") AS "VALUE"
FROM "FACT_O2C_ORDER"
GROUP BY "ORDER_STATUS";

-- 2) Të ardhurat sipas muajit (sipas datës së faturës)
CREATE OR REPLACE VIEW "V_KPI_REVENUE_MONTHLY" AS
SELECT
  YEAR("INVOICE_DATE") AS "YEAR",
  MONTH("INVOICE_DATE") AS "MONTH",
  SUM("VALUE") AS "INVOICED_VALUE",
  COUNT(*) AS "INVOICES",
  "CURRENCY"
FROM "FACT_O2C_ORDER"
WHERE "INVOICE_NO" IS NOT NULL AND "INVOICE_DATE" IS NOT NULL
GROUP BY YEAR("INVOICE_DATE"), MONTH("INVOICE_DATE"), "CURRENCY";

-- 3) Cycle time O2C (ditë nga porosia deri te goods issue)
CREATE OR REPLACE VIEW "V_KPI_CYCLE_TIME" AS
SELECT
  "IDSO", "ZINN",
  DAYS_BETWEEN("CREATED", "GI_DATE") AS "ORDER_TO_GI_DAYS",
  DAYS_BETWEEN("CREATED", "INVOICE_DATE") AS "ORDER_TO_INVOICE_DAYS"
FROM "FACT_O2C_ORDER"
WHERE "GI_DATE" IS NOT NULL;

-- 4) On-time delivery rate (goods issue brenda 5 ditëve nga porosia)
CREATE OR REPLACE VIEW "V_KPI_ONTIME" AS
SELECT
  COUNT(*) AS "TOTAL_SHIPPED",
  SUM(CASE WHEN DAYS_BETWEEN("CREATED","GI_DATE") <= 5 THEN 1 ELSE 0 END) AS "ON_TIME",
  ROUND(100.0 * SUM(CASE WHEN DAYS_BETWEEN("CREATED","GI_DATE") <= 5 THEN 1 ELSE 0 END) / NULLIF(COUNT(*),0), 1) AS "ON_TIME_PCT"
FROM "FACT_O2C_ORDER"
WHERE "GI_DATE" IS NOT NULL;

-- 5) DSO i thjeshtuar (mesatarja ditë porosi->pagesë) & open A/R
CREATE OR REPLACE VIEW "V_KPI_AR" AS
SELECT
  SUM(CASE WHEN "FI_STATUS" <> 'CLEARED' AND "INVOICE_NO" IS NOT NULL THEN "VALUE" ELSE 0 END) AS "OPEN_AR",
  SUM(CASE WHEN "FI_STATUS" = 'CLEARED' THEN "PAID_AMOUNT" ELSE 0 END) AS "COLLECTED",
  COUNT(CASE WHEN "FI_STATUS" <> 'CLEARED' AND "INVOICE_NO" IS NOT NULL THEN 1 END) AS "OPEN_ITEMS"
FROM "FACT_O2C_ORDER";

-- 6) Top produkte sipas vlerës
CREATE OR REPLACE VIEW "V_KPI_TOP_PRODUCTS" AS
SELECT "SALTCODE", "TITLE", COUNT(*) AS "ORDERS",
       SUM("QUANTITY") AS "QTY", SUM("VALUE") AS "VALUE"
FROM "FACT_O2C_ORDER"
GROUP BY "SALTCODE", "TITLE"
ORDER BY SUM("VALUE") DESC;

-- 7) Përmbledhje headline (një rresht për KPI cards)
CREATE OR REPLACE VIEW "V_KPI_HEADLINE" AS
SELECT
  (SELECT COUNT(*) FROM "FACT_O2C_ORDER") AS "TOTAL_ORDERS",
  (SELECT SUM("VALUE") FROM "FACT_O2C_ORDER") AS "TOTAL_VALUE",
  (SELECT COUNT(*) FROM "FACT_O2C_ORDER" WHERE "ORDER_STATUS"='PAID') AS "PAID_ORDERS",
  (SELECT "ON_TIME_PCT" FROM "V_KPI_ONTIME") AS "ON_TIME_PCT",
  (SELECT "OPEN_AR" FROM "V_KPI_AR") AS "OPEN_AR"
FROM DUMMY;
